title       = "devdocs"
baseURL     = "https://devdocs-cli.tamnd.com/"
description = "Browse DevDocs.io programming documentation"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/devdocs-cli"
